[env:esp32-s3-motor]
platform = espressif32
framework = arduino
board = esp32-s3-devkitc-1-n16r8
monitor_speed = 115200
build_type = debug
build_flags =
  -DCORE_DEBUG_LEVEL=2
extra_scripts = post:extra_script.py

